---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: ublue-ratz-laptop-nvidia
# description will be included in the image's metadata
description: Ublue image for nvidia laptops

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      nonfree: negativo17

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/lukenukem/asus-linux/repo/fedora-%OS_VERSION%/lukenukem-asus-linux-fedora-%OS_VERSION%.repo
    install:
      - asusctl
      - supergfxctl
      - asusctl-rog-gui
      - plasma-discover-rpm-ostree
      - winesync
      - tailscale
      - steam-devices
      - lm_sensors
      - distrobox
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

#  - type: akmods
#    base: main
#    install:
#      - nvidia
  - type: kargs
    arch: x86_64
    kargs:
      - nvidia-drm.modeset=1
      - modprobe.blacklist=nouveau
      - rd.driver.blacklist=nouveau

  - type: script
    scripts:
    - installnvidiakmod.sh
    - installnvidiapackages.sh
    - setearlyloading.sh
#    - setdrmvariables.sh

  - type: systemd
    system:
      enabled:
        - nvidia-suspend.service
        - nvidia-hibernate.service
        - nvidia-resume.service

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - net.waterfox.waterfox
        - io.missioncenter.MissionCenter
        # KDE Desktop Flatpaks
        - org.kde.kphotoalbum
        - org.kde.gwenview
        - org.kde.kate
        - org.kde.okular
        - org.kde.kcalc
        - org.kde.kontact
        - org.kde.filelight
        - org.kde.konsole
        - org.kde.ark
        - org.kde.krdc
        - org.kde.skanpage
        - org.kde.kamoso
        - org.kde.marknote
        # Basic
        - com.github.tchx84.Flatseal
        - org.fkoehler.KTailctl
        - it.mijorus.gearlever
        - com.usebottles.bottles
        - io.github.dvlv.boxbuddyrs
        - com.github.zocker_160.SyncThingy
        - org.videolan.VLC
        - org.gnome.World.PikaBackup
        # Misc
        - com.discordapp.Discord
        - org.localsend.localsend_app
        - com.transmissionbt.Transmission
        - com.dec05eba.gpu_screen_recorder
        # Creative
        - org.kde.krita
        - com.ultimaker.cura
        - org.kde.kdenlive
        # Office Tools
        - com.github.jeromerobert.pdfarranger
        - org.onlyoffice.desktopeditors
        # Games
        - org.prismlauncher.PrismLauncher
        - com.github.Matoking.protontricks
        - com.valvesoftware.Steam
        - com.heroicgameslauncher.hgl
        - org.vinegarhq.Sober
#      remove:
#        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

